### PR TITLE
Adding table, removing comments, and doing some edits.

### PR DESCRIPTION
**Pull request by sonyahanson**
Adding table, removing comments, and doing some edits.

### CODE REVIEW

**Comment by sonyahanson** [comment]
This is all done! Added in the table of results and a few figures. Also unified our statement of '68 kinases expressed better than 2 ng/ul', in some parts of it said 51 kinases... Also commented out comments and added 'Klock and colleagues' reference the supports the claim of varying N- and C- termini to improve expression:

> In expressing a protein domain, the choice of the N- and C-terminal boundaries represents an important consideration because even small differences can dramatically influence both solubility and expression. For example, Klock and colleagues evaluated a nested set of 2,143 N- and C-terminal truncations from 96 targets and found considerable variation in both solubility and aggregation behavior by altering the protein length by just a few amino acids.

Quote is from [this](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3178102/) SGC review on protein production and expression.

**Comment by jchodera** [comment]
Awesome!  I'm going through this and will try to finish my edits around noon.

Regarding the 2 ng/uL: I remember this part being confusing.  From what I recall, they elute from the beads a total of 80 uL (though the manuscript says they then wash with an additional 40 uL).  Previously, I believe Scott described that they ran a few uL of this 80 uL through the Caliper for quantitation.  Danny and I tried to figure out how many mg/mL of culture this meant, and those columns are also in the online table.  I don't think we need to change the reporting of this right now---just something we should clarify in the future, and hopefully add an "expected mg/mL culture following purification" just to make it easier for people to see something in units they understand.

**Comment by Lucelenie** [comment]
Hi John,

I just made a commit to the master that includes more details from the
MacroLab expression testing that Chris emailed me yesterday.

On Tue, Feb 2, 2016 at 10:57 AM, John Chodera notifications@github.com
wrote:

> Awesome! I'm going through this and will try to finish my edits around
> noon.
> 
> Regarding the 2 ng/uL: I remember this part being confusing. From what I
> recall, they elute from the beads a total of 80 uL (though the manuscript
> says they then wash with an additional 40 uL). Previously, I believe Scott
> described that they ran a few uL of this 80 uL through the Caliper for
> quantitation. Danny and I tried to figure out how many mg/mL of culture
> this meant, and those columns are also in the online table. I don't think
> we need to change the reporting of this right now---just something we
> should clarify in the future, and hopefully add an "expected mg/mL culture
> following purification" just to make it easier for people to see something
> in units they understand.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/choderalab/kinase-ecoli-expression-panel/pull/8#issuecomment-178652802
> .

## 

Lucelenie Rodríguez-Laureano
Research Technician, Chodera Lab
Memorial Sloan Kettering Cancer Center
646.888.2628

**Comment by jchodera** [comment]
Thanks!  Will work on that version instead.

**Comment by jchodera** [comment]
Please work through pull requests in the future when possible!  We don't get updates of changes otherwise.

**Pull request merged**
